version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: recipe-postgres
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recipes"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - recipe-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: recipes
      DB_USER: postgres
      DB_PASSWORD: password123
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  recipe-network:
    driver: bridge
