openapi: 3.0.3
info:
  title: Recipe API
  description: A REST API for managing recipes with ingredients, instructions, and nutritional information
  version: 1.0.0
  contact:
    name: Recipe API Support
servers:
  - url: http://localhost:3001
    description: Local development server
  - url: http://192.168.40.142:3001
    description: Production server

paths:
  /health:
    get:
      summary: Health check
      description: Check if the API is running and healthy
      tags:
        - Health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  message:
                    type: string
                    example: "Recipe API is running"

  /api/recipes:
    get:
      summary: Get all recipes
      description: Retrieve a list of all recipes with their ingredients, instructions, and tags
      tags:
        - Recipes
      responses:
        '200':
          description: List of recipes retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new recipe
      description: Create a new recipe with ingredients, instructions, and nutritional information
      tags:
        - Recipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/RecipeInput'
                - type: array
                  items:
                    type: object
                    properties:
                      output:
                        $ref: '#/components/schemas/RecipeInput'
            examples:
              direct:
                summary: Direct recipe input
                value:
                  title: "Chicken Stir Fry"
                  servings: 4
                  ingredients: ["1 lb chicken breast", "2 cups broccoli", "1 bell pepper"]
                  instructions: ["Cut chicken into pieces", "Stir fry chicken", "Add vegetables"]
                  macros_per_serving:
                    calories: 350
                    protein_g: 35
                    carbs_g: 15
                    fat_g: 12
                  tags: ["chicken", "stir-fry", "healthy"]
                  notes: "Quick and easy dinner recipe"
              n8n:
                summary: n8n workflow format
                value:
                  - output:
                      title: "Chicken Stir Fry"
                      servings: 4
                      ingredients: ["1 lb chicken breast", "2 cups broccoli", "1 bell pepper"]
                      instructions: ["Cut chicken into pieces", "Stir fry chicken", "Add vegetables"]
                      macros_per_serving:
                        calories: 350
                        protein_g: 35
                        carbs_g: 15
                        fat_g: 12
                      tags: ["chicken", "stir-fry", "healthy"]
                      notes: "Quick and easy dinner recipe"
      responses:
        '201':
          description: Recipe created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Recipe created successfully"
                  recipeId:
                    type: integer
                    example: 123
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/recipes/{id}:
    get:
      summary: Get recipe by ID
      description: Retrieve a specific recipe by its ID
      tags:
        - Recipes
      parameters:
        - name: id
          in: path
          required: true
          description: Recipe ID
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Recipe retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: Recipe not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          description: Unique recipe identifier
          example: 1
        title:
          type: string
          description: Recipe title
          example: "Chicken Stir Fry"
        servings:
          type: integer
          description: Number of servings
          example: 4
        calories:
          type: integer
          description: Calories per serving
          example: 350
        protein_g:
          type: number
          description: Protein in grams per serving
          example: 35.0
        carbs_g:
          type: number
          description: Carbohydrates in grams per serving
          example: 15.0
        fat_g:
          type: number
          description: Fat in grams per serving
          example: 12.0
        notes:
          type: string
          description: Additional notes about the recipe
          example: "Quick and easy dinner recipe"
        ingredients:
          type: array
          description: List of ingredients
          items:
            type: string
          example: ["1 lb chicken breast", "2 cups broccoli", "1 bell pepper"]
        instructions:
          type: array
          description: Step-by-step cooking instructions
          items:
            type: string
          example: ["Cut chicken into pieces", "Stir fry chicken", "Add vegetables"]
        tags:
          type: array
          description: Recipe tags for categorization
          items:
            type: string
          example: ["chicken", "stir-fry", "healthy"]
        created_at:
          type: string
          format: date-time
          description: Recipe creation timestamp
          example: "2023-12-01T10:00:00Z"

    RecipeInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Recipe title
          example: "Chicken Stir Fry"
        servings:
          type: integer
          description: Number of servings
          default: 1
          example: 4
        ingredients:
          type: array
          description: List of ingredients
          items:
            type: string
          example: ["1 lb chicken breast", "2 cups broccoli", "1 bell pepper"]
        instructions:
          type: array
          description: Step-by-step cooking instructions
          items:
            type: string
          example: ["Cut chicken into pieces", "Stir fry chicken", "Add vegetables"]
        macros_per_serving:
          type: object
          description: Nutritional information per serving
          properties:
            calories:
              type: integer
              description: Calories per serving
              example: 350
            protein_g:
              type: number
              description: Protein in grams per serving
              example: 35.0
            carbs_g:
              type: number
              description: Carbohydrates in grams per serving
              example: 15.0
            fat_g:
              type: number
              description: Fat in grams per serving
              example: 12.0
        tags:
          type: array
          description: Recipe tags for categorization
          items:
            type: string
          example: ["chicken", "stir-fry", "healthy"]
        notes:
          type: string
          description: Additional notes about the recipe
          example: "Quick and easy dinner recipe"

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Internal server error"

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication (if implemented)
